#%RAML 1.0
title: lcsTracker
baseUri: http://urlhere.com/{version}
version: v1

types:
  typeTeam: !include types/typeTeam.raml
  typePlayer: !include types/typePlayer.raml
  

/players:
  description: "collection of all currently active professional players"
  post:
    description: "add a new player of playerID to the league"
    body:
      application/json:
        type: typePlayer
        example: !include examples/player.example
    responses:
      201:
        body:
          application/json:
            example: !include successCode.example
  get:
    description: "get a list of players in a specific region"
    queryParameters:
      region: 
        type: string
        required: true
        minLength: 2
        maxLength: 3
    responses:
      200:
        body:
          application/json:
            type: typePlayer[]
        
  /{playerId}:
    uriParameters:
      playerId:
        type: string
    get:
      description: "get a player by their ID"
      responses:
        200:
          body:
            application/json:
              type: typePlayer
              example: !include examples/player.example
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Player not found"
                }
    put:
      description: "update info of a specific player"
      body:
        application/json:
          type: typePlayer
          example: !include examples/player.example
      response:
        201:
          body:
            application/json:
              example: !include successCode.example
    delete:
      description: "removes the entry for playerId"
      responses:
        204:
          body:
            application/json:
              example: !include successCode.example

/teams:
  description: "collection of all active professional teams"
  post:
    description: "adds new team to the active database"
    body:
      application/json:
        type: typeTeam
        example: !include examples/team.example
    responses:
      201:
        body:
          application/json:
            example: !include successCode.example
  get:
    description: "get list of teams from given region"
    queryParameters:
      region:
        type: string
        minLength: 2
        maxLength: 3
    responses:
      200:
        body:
          application/json:
            type: typeTeam[]
  /{teamTag}:
    uriParameters:
      teamTag:
        type: string
    get:
      description: "get the team info for the team tag"
      responses:
        200:
          body:
            application/json:
              type: typeTeam
              example: !include examples/team.example
    put:
      description: "update team info"
      body:
        application/json:
          type: typeTeam
          example: !include examples/team.example
      responses:
        201:
          body:
            application/json:
              example: !include successCode.example
    delete:
      description: "remove the team from the db"
      responses:
        204:
          body:
            application/json:
              example: !include successCode.example
